### ISSUE TITLE
PPTransTPTP: possible problem with translating enumerated sets

### ISSUE THREAD

**Issue by Daniel-Crowle** [CLEARSY/pptranssmt#18]
# Possible Problem
Included is a machine that was not expected to be a miracle machine.

However, Vampire prover refutes the translation to TPTP. When the enumerated set, `REPORT`, is removed (which has no other business in the machine), Vampire ceases to refute a TPTP translation of the new machine.

Perhaps something in the translation to TPTP causes this issue.

# Attachments
[pptranstptp_issue.tar.gz](https://github.com/user-attachments/files/16345730/pptranstptp_issue.tar.gz)
- Club1.mch is the machine in B.
- Club1.pog is its POG file.
- Club_1-0-0.tptp is the translation of its first goal.
- vampire_result.txt is the output of Vampire when run on Club_1-0-0.tptp

**Comment by dde-cls** [comment]
Problem could also be in axioms for `isum`, as the inconsistency seems to be derived from the application of `isum` to the enumerated set (which should not make any sense... but happens since enumerated sets are plunged into INTEGER).

**Comment by dde-cls** [comment]
Analysis has shown that the axioms for isum (and iprod, rsum, rprod) are buggy. A fix should soon be available.

**Comment by dde-cls** [comment]
Problem fixed in commit 43a4c8cc6ff48ae6ab44993088b1d57732491be8.
